run:
  timeout: 5m
  tests: false
  modules-download-mode: readonly

issues:
  exclude-use-default: false
  exclude-dirs:
    - .encore
    - spec
    - static

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - revive

linters-settings:
  revive:
    ignore-generated-header: true
